name:                translato
version:             0.1.0.0
github:              "githubuser/translato"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/translato#readme>

default-extensions:
- DerivingStrategies
- DeriveGeneric
- DeriveAnyClass
- OverloadedStrings
- TypeSynonymInstances
- FlexibleInstances
- MultiParamTypeClasses
- InstanceSigs
- FlexibleContexts
- OverloadedLabels
- DuplicateRecordFields
- LambdaCase
- RecordWildCards
- TypeApplications
- ScopedTypeVariables
- KindSignatures
- ConstraintKinds
- GeneralizedNewtypeDeriving
- DataKinds
- TypeOperators


dependencies:
- name: base
  mixin: hiding (Prelude)
- name: relude
  mixin: (Relude as Prelude, Relude.Extra, Relude.Unsafe)
- name: aeson
- name: optparse-generic
- name: generic-lens
- name: lens
- name: comonad
- name: containers
- name: safe
- name: threepenny-gui
- name: cond
- name: data-fix
- name: unagi-chan
- name: mtl
- name: filepath
- name: bytestring
- name: exceptions
- name: async
- name: servant
- name: servant-server
- name: servant-client
- name: servant-docs
- name: servant-auth
- name: servant-auth-server
- name: servant-auth-client
- name: servant-auth-docs
- name: servant-conduit
- name: http-client
- name: warp
- name: uuid
- name: typed-uuid
- name: time
- name: text
- name: base16-bytestring
- name: random
- name: jose
- name: wai-cors
- name: blaze-html
- name: blaze-markup
- name: blaze-builder
- name: servant-blaze
- name: markdown
- name: cookie
- name: conduit
- name: fsnotify-conduit
- name: fsnotify
- name: resourcet


library:
  source-dirs: src

executables:
  translato-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - translato

tests:
  translato-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - translato
